# Generated by Django 5.2.1 on 2025-06-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_test_posts'),
        ('blog', '0002_post_created_on'),
    ]

    operations = [
    ]
